# 워크플로우 이름
name: Daily Labor Newsletter

# 워크플로우 실행 트리거 설정
on:
  schedule:
    - cron: '0 22 * * *' # 매일 아침 7시 (한국시간 기준)

  workflow_dispatch:

# 작업(Job) 정의
jobs:
  run-newsletter:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. GitHub 리포지토리 코드 체크아웃
      - name: 체크아웃 저장소
        uses: actions/checkout@v4

      # 2. Python 환경 설정
      - name: Python 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 의존성 라이브러리 설치
      - name: 패키지 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Python 스크립트 실행
      # 스크립트의 표준 출력(Standard Output)은 newsletter.txt로 리다이렉션됩니다.
      # 스크립트의 표준 에러(Standard Error)는 error.log로 리다이렉션됩니다.
      # 스크립트 내부에서 print(...) 는 표준 출력으로, print(..., file=sys.stderr) 는 표준 에러로 갑니다.
      - name: 뉴스레터 실행 (메일 발송 포함)
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          # 스크립트 실행 및 출력 리다이렉션 설정
          # 2> error.log 는 표준 에러를 error.log 파일로 보낸다는 의미입니다.
          # 파일이 비어있더라도 생성되도록 touch 명령 추가 (선택 사항)
          # touch newsletter.txt error.log
          python main.py > newsletter.txt 2> error.log

      # 4.5 생성된 뉴스레터 파일(newsletter.txt) 아티팩트 업로드
      # 스크립트 실행 결과인 뉴스레터 내용을 확인하기 위함입니다.
      - name: 생성된 뉴스레터 파일 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: generated-newsletter
          path: newsletter.txt
          if-no-files-found: ignore # 파일이 없으면 무시 (오류 아님)

      # 4.6 실행 중 발생한 에러 로그 파일 아티팩트 업로드
      # 스크립트 실행 중 표준 에러로 출력된 내용을 확인하기 위함입니다.
      # 스크립트에 오류가 없었다면 이 파일은 비어있거나 존재하지 않을 수 있습니다.
      - name: 에러 로그 파일 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: error-log
          path: error.log
          if-no-files-found: ignore # 파일이 없으면 무시 (오류 아님)


      # 5. 결과물 자동 커밋 및 푸시
      # 스텝 4에서 newsletter.txt 파일에 변경사항이 생겼는지 감지합니다.
      - name: 결과물 자동 커밋
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          files: newsletter.txt # newsletter.txt 파일만 커밋 대상으로 명시
          commit_message: "뉴스레터 자동 업데이트 - $(date +'%Y-%m-%d')"
          # commit_user_name: 'GitHub Actions Bot'
          # commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          # token: ${{ secrets.GITHUB_TOKEN }}
